---
title: 'data formatting'

---

```{r, include=FALSE}
knitr::opts_chunk$set(cache=TRUE, autodep=TRUE, cache.comments=TRUE)
```



- **1.** Loading Data
```{r}

#source: https://towardsdatascience.com/using-weighted-k-means-clustering-to-determine-distribution-centres-locations-2567646fc31d



library(dplyr)

coord.df = read.csv(file= "coord2_clean.csv", header=T)
coord.df
na.omit(coord.df)
coord.df

coord.df[-which(coord.df$Long == 0), ]
```


- **2.** Haversine Distance Function
```{r}

haversine_dist = function(point1, point2){
  long1 = point1[1]
  lat1 = point1[2]
  long2 = point2[1]
  lat2 = point2[2]
  
  R = 6371000 #earth radius in meters
  phi1 = lat1 * pi / 180 #convert to radian
  phi2 = lat2 * pi / 180 #convert to radian
  delta_phi = (lat2 - lat1) * pi / 180
  delta_lambda = (long2 - long1) * pi / 180
  
  a = (sin(delta_phi/2))^2 + cos(phi1) * cos(phi2) * ((sin(delta_lambda/2))^2)
  c = 2 * atan2(sqrt(a), sqrt(1-a))
  
  distance = R * c #haversine distance between point1 and point 2 in meters
  return(round(distance, 2))
}

```


- **3.** SSE Function
```{r}

SSE = function(coord.df, clustering) { 
  #coord_df is a dataframe with columns: county name, longitude, latitude, cases
  #clustering is vector of cluster assignment of counties
  
  #prepare argument
  longlat_mat = as.matrix.data.frame(coord.df[,4:3])
  colnames(longlat_mat) = NULL
  
  #compute centroid
  centroid_long = vector()
  centroid_lat = vector()
  for (k in c(1:max(clustering))) {
    cluster_k = which(clustering == k) #city index of cluster k
    centroid_long[k] = weighted.mean(coord.df$Long[cluster_k], coord.df$Cases[cluster_k])
    centroid_lat[k] = weighted.mean(coord.df$Lat[cluster_k], coord.df$Cases[cluster_k])
  }
  mat_centroid = cbind(centroid_long, centroid_lat)
  colnames(mat_centroid) = NULL
  
  #compute SSE
  sum_squares_err = 0
  for (k in c(1:max(clustering))) {
    cluster_k = which(clustering == k) #city index of cluster k
    for (i in c(1:length(cluster_k))) {
      for (j in c(1:2)) { #long, lat
        square_err = (longlat_mat[cluster_k[i],j] - mat_centroid[k,j])^2
        sum_squares_err = sum_squares_err + square_err
      }
    }
  }
  return(sum_squares_err)
}

```


- **4.** Elbow ethod for finding optimal K
```{r}

library(ggplot2)

#initiate container
vect_see = data.frame()
k = 10

#fill vect_see via looping
for (K in c(1:k)) {
  print(K)
  for (i in c(1:10)) {
    cluster_assignment = weighted_kmeans(coord.df, K)
    vect_see[i, K] = SSE(coord.df, cluster_assignment)
  }
}


for (K in c(1:k)) {
  vect_see[11, K] = mean(vect_see[c(1:10), K])
}


#create data frame to use ggplot
df_elbow = data.frame()
for (i in 2:10) {
  df_elbow[i - 1, 1] = i
  df_elbow[i - 1, 2] = vect_see[11, i]
}
names(df_elbow) = c("number_cluster", "SSE")

df_elbow

#plotting SSE decline over K (number of clusters)
ggplot(data = df_elbow, aes(x = number_cluster, y = SSE)) + geom_line(color = 'skyblue') + geom_point(color = 'red', size = 3)

```



**5. ** K-means
```{r}

weighted_kmeans = function(coord.df,K){
  
  #initial centroids by random
  init_centroids_index = sample(nrow(coord.df),K)
  #initiate containers
  distance_matrix = matrix(data = NA, nrow = nrow(coord.df), ncol = K)
  cluster = vector()
  centroid_long = vector()
  centroid_lat = vector()
  #compute distance between counties and initial centroids
  for (k in c(1:K)) {
    for (i in c(1:nrow(coord.df))) {
      county_i = as.numeric(coord.df[i,4:3])
      centroid_k = as.numeric(coord.df[init_centroids_index[k],4:3])
      distance_matrix[i,k] = haversine_dist(county_i,centroid_k)
    }
  }
  #initial cluster assignment for each county
  for (i in c(1:nrow(coord.df))) {
    cluster[i] = which.min(distance_matrix[i,])
  }
  
  
  
  #iteration baseline
  old_cluster = vector(length = length(cluster))
  new_cluster = cluster
  #iterations
  while (!all(old_cluster == new_cluster)) {
    #update old cluster assignment
    old_cluster = new_cluster
    #calculate centroids using weighted average
    for (k in c(1:K)) {
      cluster_k = which(old_cluster == k) #city index of cluster k
      centroid_long[k] = weighted.mean(coord.df$Long[cluster_k], coord.df$Cases[cluster_k])
      centroid_lat[k] = weighted.mean(coord.df$Lat[cluster_k], coord.df$Cases[cluster_k])
    }
    df_centroid = as.data.frame(cbind(centroid_long, centroid_lat))
    #compute distance between counties and centroids
    for (k in c(1:K)) {
      for (i in c(1:nrow(coord.df))) {
        county_i = as.numeric(coord.df[i,4:3])
        centroid_k = as.numeric(df_centroid[k,])
        if (is.na(centroid_k[2])){print(c(k,i))
        }
        distance_matrix[i,k] = haversine_dist(county_i,centroid_k)
      }
    }
    #update cluster assignment for each city
    for (i in c(1:nrow(coord.df))) {
      cluster[i] = which.min(distance_matrix[i,])
    }
    #update new_cluster
    new_cluster = cluster
  }
  #print(df_centroid)
  return(cluster) #cluster assignment
}
```


**5. ** Plotting Clusters
```{r}
K = 7 #optimal K from elbow method
cluster_assignment = weighted_kmeans(coord.df, K)
df_city_cluster = as.data.frame(cbind(longitude = coord.df$Long, latitude = coord.df$Lat, cluster = cluster_assignment))

#calculate centroids (weighted average)
centroid_long = vector()
centroid_lat = vector()

for (k in c(1:K)) {
  cluster_k = which(cluster_assignment == k) #city index of cluster k
  centroid_long[k] = weighted.mean(coord.df$Long[cluster_k], coord.df$Cases[cluster_k])
  centroid_lat[k] = weighted.mean(coord.df$Lat[cluster_k], coord.df$Cases[cluster_k])
}

#create data frame for centroid with dummy cluster number 
df_centroid = as.data.frame(cbind(longitude = centroid_long, latitude = centroid_lat, cluster = rep(K+1, length(centroid_lat))))

#append df_city_cluster and df_centroid for ggplot
df_kmeans_result = rbind.data.frame(df_city_cluster, df_centroid)

#the plot
#clusters
plot(df_kmeans_result$longitude[which(df_kmeans_result$cluster==1)],
     df_kmeans_result$latitude[which(df_kmeans_result$cluster==1)],
     col="violetred3",pch=19,
     xlim = c(min(df_kmeans_result$longitude)-0.75,max(df_kmeans_result$longitude)+0.75), 
     ylim=c(10,50),xlab = "longitude", ylab = "latitude",main = "Factory Locations based on Weighted K-means")
points(df_kmeans_result$longitude[which(df_kmeans_result$cluster==2)],df_kmeans_result$latitude[which(df_kmeans_result$cluster==2)],col="cadetblue",pch=19)
points(df_kmeans_result$longitude[which(df_kmeans_result$cluster==3)],df_kmeans_result$latitude[which(df_kmeans_result$cluster==3)],col="antiquewhite",pch=19)
points(df_kmeans_result$longitude[which(df_kmeans_result$cluster==4)],df_kmeans_result$latitude[which(df_kmeans_result$cluster==4)],col="cadetblue1",pch=19)
points(df_kmeans_result$longitude[which(df_kmeans_result$cluster==5)],df_kmeans_result$latitude[which(df_kmeans_result$cluster==5)],col="antiquewhite3",pch=19)
points(df_kmeans_result$longitude[which(df_kmeans_result$cluster==6)],df_kmeans_result$latitude[which(df_kmeans_result$cluster==6)],col="antiquewhite4",pch=19)
points(df_kmeans_result$longitude[which(df_kmeans_result$cluster==7)],df_kmeans_result$latitude[which(df_kmeans_result$cluster==7)],col="antiquewhite2",pch=19)

#centroids
points(df_kmeans_result$longitude[which(df_kmeans_result$cluster==8)],df_kmeans_result$latitude[which(df_kmeans_result$cluster==8)],col="black",pch=7)
```


